### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by forlin** [bugcrowd/HUNT#10]
load burp extension error

`Traceback (most recent call last):
  File "E:\github\HUNT\hunt_methodology.py", line 47, in __init__
    self.view = View()
  File "E:\github\HUNT\hunt_methodology.py", line 214, in __init__
    self.set_tabbed_panes()
  File "E:\github\HUNT\hunt_methodology.py", line 299, in set_tabbed_panes
    tabbed_pane = self.set_tabbed_pane(functionality_name, test_name)
  File "E:\github\HUNT\hunt_methodology.py", line 312, in set_tabbed_pane
    self.tabbed_pane = JTabbedPane()
	at javax.swing.plaf.nimbus.NimbusStyle.getFontForState(Unknown Source)

	at javax.swing.plaf.synth.SynthStyle.installDefaults(Unknown Source)

	at javax.swing.plaf.nimbus.NimbusStyle.installDefaults(Unknown Source)

	at javax.swing.plaf.synth.SynthStyle.installDefaults(Unknown Source)

	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(Unknown Source)

	at javax.swing.plaf.synth.SynthTabbedPaneUI.updateStyle(Unknown Source)

	at javax.swing.plaf.synth.SynthTabbedPaneUI.installDefaults(Unknown Source)

	at javax.swing.plaf.basic.BasicTabbedPaneUI.installUI(Unknown Source)

	at javax.swing.JComponent.setUI(Unknown Source)

	at javax.swing.JTabbedPane.setUI(Unknown Source)

	at javax.swing.JTabbedPane.updateUI(Unknown Source)

	at javax.swing.JTabbedPane.<init>(Unknown Source)

	at javax.swing.JTabbedPane.<init>(Unknown Source)

	at sun.reflect.GeneratedConstructorAccessor46.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)

java.lang.ClassCastException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.awt.Font

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.Py.JavaError(Py.java:537)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:221)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:180)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at org.python.core.PyObject.__call__(PyObject.java:449)
	at org.python.pycode._pyx1.set_tabbed_pane$41(E:\github\HUNT\hunt_methodology.py:316)
	at org.python.pycode._pyx1.call_function(E:\github\HUNT\hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.set_tabbed_panes$39(E:\github\HUNT\hunt_methodology.py:294)
	at org.python.pycode._pyx1.call_function(E:\github\HUNT\hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx1.__init__$28(E:\github\HUNT\hunt_methodology.py:216)
	at org.python.pycode._pyx1.call_function(E:\github\HUNT\hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at org.python.core.PyObject.__call__(PyObject.java:449)
	at org.python.pycode._pyx1.__init__$5(E:\github\HUNT\hunt_methodology.py:47)
	at org.python.pycode._pyx1.call_function(E:\github\HUNT\hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.ngf.<init>(Unknown Source)
	at burp.a3f.a(Unknown Source)
	at burp.s8b.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.awt.Font
	at javax.swing.plaf.nimbus.NimbusStyle.getFontForState(Unknown Source)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(Unknown Source)
	at javax.swing.plaf.nimbus.NimbusStyle.installDefaults(Unknown Source)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(Unknown Source)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(Unknown Source)
	at javax.swing.plaf.synth.SynthTabbedPaneUI.updateStyle(Unknown Source)
	at javax.swing.plaf.synth.SynthTabbedPaneUI.installDefaults(Unknown Source)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.installUI(Unknown Source)
	at javax.swing.JComponent.setUI(Unknown Source)
	at javax.swing.JTabbedPane.setUI(Unknown Source)
	at javax.swing.JTabbedPane.updateUI(Unknown Source)
	at javax.swing.JTabbedPane.<init>(Unknown Source)
	at javax.swing.JTabbedPane.<init>(Unknown Source)
	at sun.reflect.GeneratedConstructorAccessor46.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
	... 56 more
`

![error](https://user-images.githubusercontent.com/3012554/29255359-2ffc5726-80d3-11e7-9d24-ed84555bca6a.jpg)

**Comment by swagnetow** [comment]
I noticed this line `at javax.swing.plaf.nimbus.NimbusStyle.installDefaults(Unknown Source)`. Did you try changing your font?

**Comment by forlin** [comment]
Okay, It works thank's!
