### ISSUE TITLE
I am not able to install hunt

### ISSUE THREAD

**Issue by unmesh92** [bugcrowd/HUNT#27]
Traceback (most recent call last):
  File "C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py", line 55, in __init__
    self.view = View(self.issues)
  File "C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py", line 111, in __init__
    self.set_scanner_panes()
  File "C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py", line 191, in set_scanner_panes
    bottom_pane = self.create_tabbed_pane()
  File "C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py", line 208, in create_tabbed_pane
    tabbed_pane.add("Advisory", JScrollPane())
	at javax.swing.AbstractButton.setUIProperty(Unknown Source)

	at javax.swing.LookAndFeel.installProperty(Unknown Source)

	at javax.swing.plaf.synth.SynthButtonUI.updateStyle(Unknown Source)

	at javax.swing.plaf.synth.SynthButtonUI.installDefaults(Unknown Source)

	at javax.swing.plaf.synth.SynthArrowButton$SynthArrowButtonUI.installDefaults(Unknown Source)

	at javax.swing.plaf.basic.BasicButtonUI.installUI(Unknown Source)

	at javax.swing.JComponent.setUI(Unknown Source)

	at javax.swing.AbstractButton.setUI(Unknown Source)

	at javax.swing.plaf.synth.SynthArrowButton.updateUI(Unknown Source)

	at javax.swing.AbstractButton.init(Unknown Source)

	at javax.swing.JButton.<init>(Unknown Source)

	at javax.swing.JButton.<init>(Unknown Source)

	at javax.swing.plaf.synth.SynthArrowButton.<init>(Unknown Source)

	at javax.swing.plaf.synth.SynthScrollBarUI$2.<init>(Unknown Source)

	at javax.swing.plaf.synth.SynthScrollBarUI.createIncreaseButton(Unknown Source)

	at javax.swing.plaf.basic.BasicScrollBarUI.installComponents(Unknown Source)

	at javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)

	at javax.swing.JComponent.setUI(Unknown Source)

	at javax.swing.JScrollBar.setUI(Unknown Source)

	at javax.swing.JScrollBar.updateUI(Unknown Source)

	at javax.swing.JScrollBar.<init>(Unknown Source)

	at javax.swing.JScrollBar.<init>(Unknown Source)

	at javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)

	at javax.swing.JScrollPane.createHorizontalScrollBar(Unknown Source)

	at javax.swing.JScrollPane.<init>(Unknown Source)

	at javax.swing.JScrollPane.<init>(Unknown Source)

	at sun.reflect.GeneratedConstructorAccessor53.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)

java.lang.ClassCastException: java.lang.ClassCastException: javax.swing.plaf.InputMapUIResource cannot be cast to java.lang.Number

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.Py.JavaError(Py.java:537)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:221)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:180)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at org.python.core.PyObject.__call__(PyObject.java:449)
	at org.python.pycode._pyx4.create_tabbed_pane$29(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py:214)
	at org.python.pycode._pyx4.call_function(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx4.set_scanner_panes$26(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py:184)
	at org.python.pycode._pyx4.call_function(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx4.__init__$13(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py:113)
	at org.python.pycode._pyx4.call_function(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx4.__init__$5(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py:55)
	at org.python.pycode._pyx4.call_function(C:\Users\protiviti\Downloads\BurpSuite_Pro_v1.7.26\HUNT-master\HUNT-master\Burp\hunt_scanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.uue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: javax.swing.plaf.InputMapUIResource cannot be cast to java.lang.Number
	at javax.swing.AbstractButton.setUIProperty(Unknown Source)
	at javax.swing.LookAndFeel.installProperty(Unknown Source)
	at javax.swing.plaf.synth.SynthButtonUI.updateStyle(Unknown Source)
	at javax.swing.plaf.synth.SynthButtonUI.installDefaults(Unknown Source)
	at javax.swing.plaf.synth.SynthArrowButton$SynthArrowButtonUI.installDefaults(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonUI.installUI(Unknown Source)
	at javax.swing.JComponent.setUI(Unknown Source)
	at javax.swing.AbstractButton.setUI(Unknown Source)
	at javax.swing.plaf.synth.SynthArrowButton.updateUI(Unknown Source)
	at javax.swing.AbstractButton.init(Unknown Source)
	at javax.swing.JButton.<init>(Unknown Source)
	at javax.swing.JButton.<init>(Unknown Source)
	at javax.swing.plaf.synth.SynthArrowButton.<init>(Unknown Source)
	at javax.swing.plaf.synth.SynthScrollBarUI$2.<init>(Unknown Source)
	at javax.swing.plaf.synth.SynthScrollBarUI.createIncreaseButton(Unknown Source)
	at javax.swing.plaf.basic.BasicScrollBarUI.installComponents(Unknown Source)
	at javax.swing.plaf.basic.BasicScrollBarUI.installUI(Unknown Source)
	at javax.swing.JComponent.setUI(Unknown Source)
	at javax.swing.JScrollBar.setUI(Unknown Source)
	at javax.swing.JScrollBar.updateUI(Unknown Source)
	at javax.swing.JScrollBar.<init>(Unknown Source)
	at javax.swing.JScrollBar.<init>(Unknown Source)
	at javax.swing.JScrollPane$ScrollBar.<init>(Unknown Source)
	at javax.swing.JScrollPane.createHorizontalScrollBar(Unknown Source)
	at javax.swing.JScrollPane.<init>(Unknown Source)
	at javax.swing.JScrollPane.<init>(Unknown Source)
	at sun.reflect.GeneratedConstructorAccessor53.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
	... 56 more

**Comment by swagnetow** [comment]
Are you still having problems with this? Usually this gets fixed by disabling and re-enabling the extension.

**Comment by swagnetow** [comment]
Closing out this issue as there was no response.
