### ISSUE TITLE
Problem when trying to load JSON File within HUNT Methodology

### ISSUE THREAD

**Issue by snoopysecurity** [bugcrowd/HUNT#44]
Hey,
I seem to be having issues trying to load an external JSON file from the settings tab of the HUNT Methodology extension. 

**Error seen from the Extender console tab**
```

Traceback (most recent call last):
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 26, in actionPerformed
    self.load_data(file_name)
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 48, in load_data
    new_tree = JTree(checklist_tree)
NameError: global name 'JTree' is not defined
Traceback (most recent call last):
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 26, in actionPerformed
    self.load_data(file_name)
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 48, in load_data
    new_tree = JTree(checklist_tree)
NameError: global name 'JTree' is not defined
Traceback (most recent call last):
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 26, in actionPerformed
    self.load_data(file_name)
  File "/root/Downloads/HUNT-master/Burp/lib/methodology_settings_action.py", line 48, in load_data
    new_tree = JTree(checklist_tree)
NameError: global name 'JTree' is not defined
```
Burp Suite version used: Burp Suite Professional 1.7.30 
Jython version: 2.7.0

Steps to recreate:
1. Try to load a JSON file such as wahh,json

**Comment by swagnetow** [comment]
@snoopysecurity Just pushed a fix. Lemme know if that works for you.

**Comment by snoopysecurity** [comment]
Fixed. Thanks :)
