### ISSUE TITLE
Error loading the extension in Burp Pro

### ISSUE THREAD

**Issue by b-u-g-s** [bugcrowd/HUNT#50]
Hi,

I wanted to try your plugin, having the latest version of BURP PRO (as of today: 1.7.34).
I did install jython a few months ago and have other extensions installed (usually through the BAapp  Store).

Downloaded your 2x .py files
Added a python extension for both of the files...
but getting the following error on loading them:
java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.l5.<init>(Unknown Source)
	at burp.i7i.a(Unknown Source)
	at burp.hrb.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

Some security warnings I need to disable somewhere? any change of having your extension on the BAapp store?

Thanks!
Bugs.

**Comment by b-u-g-s** [comment]
Just in case you ask... I am using jython 2.7.1 from brew

**Comment by Shiva108** [comment]
Got same issue, pro vs. 1.7.37

**Comment by b-u-g-s** [comment]
Actually, got it working.
First problem, what that I was actually not using a standalone jython. I thought I was, but nope.
I followed the instructions from there:
https://support.portswigger.net/customer/portal/questions/17097263-burp-extension-python-import-error

Second problem, I actually needed to do a git clone of that branch, as it is important to have the conf and lib folder along the two python files. If you don't have those folders/files then it won't find the lib required.

Hope it helps.

**Comment by 1522402210** [comment]
error：

Traceback (most recent call last):
  File "/Users/123/Downloads/HUNT_SuiteProxyExtensions/Burp/hunt_scanner.py", line 9, in <module>
    from lib.issues import Issues
ImportError: No module named lib

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx1.f$0(/Users/123/Downloads/HUNT_SuiteProxyExtensions/Burp/hunt_scanner.py:66)
	at org.python.pycode._pyx1.call_function(/Users/123/Downloads/HUNT_SuiteProxyExtensions/Burp/hunt_scanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.jn.<init>(Unknown Source)
	at burp.smb.a(Unknown Source)
	at burp.wfd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by b-u-g-s** [comment]
I had this error when I did not have the lib folder with all its content in the same directory as the hunt burp extension

**Comment by swagnetow** [comment]
Seems like the issue was solved so I'll go ahead and close this.

**Comment by devcoinfet** [comment]
issue is not closed please reopen your plugin does not work installed from burp store do u have a workaround nothing ever happens also burp pro newest version
