### ISSUE TITLE
An error occured while loading the extension.

### ISSUE THREAD

**Issue by MAH69IK** [bugcrowd/HUNT#56]
Hello!
I load Jython standalone v2.7.0 and set location to them in BurpSuite "Extender" -> "Options".
Clone repo: `git clone https://github.com/bugcrowd/HUNT`
And try load both extensions (hunt_scanner.py and hunt_methodology.py). But receive this error:
```
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.core.PySystemState.initialize(PySystemState.java:920)
	at org.python.core.PySystemState.initialize(PySystemState.java:916)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:32)
	at org.python.core.Py.getThreadState(Py.java:1440)
	at org.python.core.Py.getThreadState(Py.java:1436)
	at org.python.core.Py.getSystemState(Py.java:1456)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at burp.ohg.<init>(Unknown Source)
	at burp.spf.a(Unknown Source)
	at burp.gih.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

I need install some python modules? This is new system, so I don't have any special modules.

**Comment by techm-martin** [comment]
Did you get this issue resolved? I'm experiencing the same issue (running Burp Suite v1.7.37 on a MBP). I've tried Jython standalone v2.7.0 and v2.7.1. 

Currently trying to add hunt_methodology.py and had to make modifications to get past a couple of other errors and get this far:

1. Declare encoding at the start of the file - 
# -*- coding: utf-8 -*-
2. Modify the line below to remove the  · 
<title>HUNT/hunt_methodology.py at master · bugcrowd/HUNT</title>
to
<title>HUNT/hunt_methodology.py at master - bugcrowd/HUNT</title>

Feel I may be heading down the wrong path though.

**Comment by MAH69IK** [comment]
Look like this is my problem. I have similar problem with another extensions and don't have problem when use this in Kali Linux.
