### ISSUE TITLE
Unicode problem with issues.json

### ISSUE THREAD

**Issue by bladeism** [bugcrowd/HUNT#7]
Attached files are error logs while adding hunt_scanner.py and hunt_methodology.py. I also attached an image of burp extensions options.
![burp_settings](https://user-images.githubusercontent.com/7868059/28948768-9c220e8c-78ea-11e7-8685-0cec71ece79d.png)
[hunt_methodology_error.txt](https://github.com/bugcrowdlabs/HUNT/files/1198884/hunt_methodology_error.txt)
[huntscanner_error.txt](https://github.com/bugcrowdlabs/HUNT/files/1198885/huntscanner_error.txt)

Thank you!

**Comment by swagnetow** [comment]
@bladeism I'm not seeing any attachments. Mind posting them again?

**Comment by connectlazyguy** [comment]
I am also getting error as in the screenshot attached
![error1](https://user-images.githubusercontent.com/30702323/28937626-173d003c-78a9-11e7-8fdd-fbda50319a22.png)

**Comment by bladeism** [comment]
@swagnetow Done updating it. Thanks!

**Comment by swagnetow** [comment]
@bladeism Try unsetting "Folder for loading modules".

**Comment by bladeism** [comment]
@swagnetow Same error sir. 

Burp Suite Pro 1.7.16
Jython -stand alone 2.7.0
Win 7 SP1 64bit

**Comment by Tren** [comment]
Burp Suite Pro 1.7.12
Jython -stand alone 2.7.0
Win 7 64
@swagnetow      Being given

**Comment by connectlazyguy** [comment]
Got it working by entirely copying the hunt folder contents inside the folder where burp is installed.  I think the error is because of os.getcwd(retrieving the current directory in "os.getcwd() + os.sep + "conf" + os.sep + "checklist.json". os,getcwd is giving the path where burp is installed.

**Comment by bladeism** [comment]
@connectlazyguy I'll try this when I got home. Thanks!

**Comment by Tren** [comment]
@swagnetow   According to your approach, still did not solve the problem.
![ayd 2uif yg6miqwv j](https://user-images.githubusercontent.com/20461924/29078125-1d977dea-7c8c-11e7-89e4-18933bf0174b.png)

**Comment by swagnetow** [comment]
I'm not sure why os.getcwd() is not getting the current working directory of where the HUNT files are for you guys. I just tried the plugin as it currently is in master in Windows 10 and was able to run it fine in Burp Suite. I'll investigate further.

Windows 10
Burp Suite v1.7.26
Jython Standalone 2.7.0

**Comment by bladeism** [comment]
I don't have an error regarding issues.json

but got this instead
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 526-528: invalid data

**Comment by swagnetow** [comment]
@bladeism Mind creating a separate issue with more details so I can debug? Thanks.

**Comment by swagnetow** [comment]
@bladeism Do you mind creating another issue for your Unicode issue? Looks like there were two separate issues here and everything got jumbled up.

**Comment by ladyleet1337** [comment]
@swagnetow I am also getting the same error.

**Comment by gorgiaxx** [comment]
Same error.
java version 1.8.0_141
Burp Suite Pro 1.7.13
Jython Standalone 2.7.0

**Comment by sonahri** [comment]
same here

Traceback (most recent call last):
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 41, in run
    self.runner()
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 47, in __init__
    self.view = View()
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 207, in __init__
    self.data = Data()
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 169, in __init__
    self.set_checklist(None)
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 176, in set_checklist
    file_name = os.getcwd() + os.sep + "conf" + os.sep + "checklist.json"
IOError: [Errno 2] No such file or directory: '/root/conf/checklist.json'
Traceback (most recent call last):
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 47, in __init__
    self.view = View()
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 207, in __init__
    self.data = Data()
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 169, in __init__
    self.set_checklist(None)
  File "/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py", line 176, in set_checklist
    file_name = os.getcwd() + os.sep + "conf" + os.sep + "checklist.json"
IOError: (2, 'No such file or directory', '/root/conf/checklist.json')

	at org.python.core.Py.IOError(Py.java:226)
	at org.python.core.io.FileIO.<init>(FileIO.java:102)
	at org.python.core.PyFile.file___init__(PyFile.java:177)
	at org.python.core.PyFile$exposed___new__.createOfType(Unknown Source)
	at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12)
	at org.python.core.PyType.invokeNew(PyType.java:494)
	at org.python.core.PyType.type___call__(PyType.java:1706)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.OpenFunction.__call__(__builtin__.java:1725)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx1.set_checklist$21(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py:180)
	at org.python.pycode._pyx1.call_function(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx1.__init__$20(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py:170)
	at org.python.pycode._pyx1.call_function(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at org.python.core.PyObject.__call__(PyObject.java:449)
	at org.python.pycode._pyx1.__init__$28(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py:216)
	at org.python.pycode._pyx1.call_function(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyFunction.__call__(PyFunction.java:476)
	at org.python.core.PyInstance.__init__(PyInstance.java:124)
	at org.python.core.PyClass.__call__(PyClass.java:193)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at org.python.core.PyObject.__call__(PyObject.java:449)
	at org.python.pycode._pyx1.__init__$5(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py:47)
	at org.python.pycode._pyx1.call_function(/root/Burp Suite Professional 1.7.17/HUNT/hunt_methodology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.m1d.<init>(Unknown Source)
	at burp.llg.a(Unknown Source)
	at burp.lub.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sonahri** [comment]
solved it...just moved my conf file to root folder ..and it worked...great work keep it up

**Comment by Tren** [comment]
@sonahri     Is moved to the root directory of HUNT?

**Comment by sonahri** [comment]
check line 10...IOError: [Errno 2] No such file or directory: '/root/conf/checklist.json'
Traceback (most recent call last):
just moved conf folder to root...and it worked

**Comment by bladeism** [comment]
Anyone solved the unicode error?

**Comment by therzv** [comment]
i solve this issue by copy "conf" directory in HUNT master, to where burp working directory / installed.
